accounts/urls.py
from django.urls import path
from . import views
from .views import SignUpView, SignInView
from django.contrib.auth.decorators import login_required


app_name = 'accounts'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signin/', SignInView.as_view(), name='signin'),

    # ログアウトは認証後に使うものなので login_required
    path('signout/', login_required(views.signout), name='signout'),
]

snsapp/urls.py
from django.urls import path
from .views import HomeView,MyHomeView,PostCreateView,PostDeleteView,PostDetailView,PostEditView,ProfileView,ProfileCreateView,ProfileEditView
from django.contrib.auth.decorators import login_required


app_name = 'snsapp'

urlpatterns = [
    path('', login_required(HomeView.as_view()), name='home'),
    path('my_home/', login_required(MyHomeView.as_view()), name='my_home'),
    path('create/', login_required(PostCreateView.as_view()), name='post_create'),
    path('post/<int:pk>/delete/', login_required(PostDeleteView.as_view()), name='post_delete'),
    path('post/<int:pk>/', login_required(PostDetailView.as_view()), name='post_detail'),
    path('post/<int:pk>/edit/', login_required(PostEditView.as_view()), name='post_edit'),
    path('profile/', login_required(ProfileView.as_view()), name='profile'),

    # 機能していないプロフィール関連のurl
    path('profile/create/', login_required(ProfileCreateView.as_view()), name='profile_create'),
    path('profile/edit/', login_required(ProfileEditView.as_view()), name='profile_edit'),
]

snsproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # 追加
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('snsapp.urls')),
]

# メディアファイルの設定
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 追加

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):

    USERNAME_FIELD = 'username'

    def __str__(self):
        return self.username

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser


#class SignUpForm(UserCreationForm):
    #class Meta:
        #model = CustomUser
        #fields = ('username', 'email')
        # fields = ['username', 'email', 'password']
        # labels = {
        #     'username': 'ユーザー名',
        #     'email': 'メールアドレス',
        #     'password': 'パスワード',
        # }
        # widgets = {
        #     'password': forms.PasswordInput(),
        # }


class SignInForm(forms.Form):
    username = forms.CharField(label='ユーザー名')
    password = forms.CharField(label='パスワード', widget=forms.PasswordInput)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.hashers import make_password
from django.urls import reverse,reverse_lazy
from django.http import HttpResponseRedirect
from .forms import SignInForm #SignUpForm, 
from .models import CustomUser
from django.views.generic import CreateView, TemplateView, FormView

def index(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('snsapp:home'))
    return render(request, 'accounts/index.html')


# サインアップ
class SignUpView(CreateView):
    #form_class = SignUpForm
    model = CustomUser
    fields = ("username","email","password")
    template_name = "accounts/signup.html"
    # success_url = reverse_lazy('snsapp:home')
    success_url = reverse_lazy('accounts:index')

    def post(self,request,*args,**kwargs):
        username = request.POST['username']
        email = request.POST['email']
        password2 = request.POST['password']
        password = make_password(password2)
        user = CustomUser(username=username, email=email, password=password)
        user.save()
        login(self.request, user)
        return HttpResponseRedirect(reverse('snsapp:home'))

# サインイン（ログイン）
class SignInView(FormView):
    template_name = 'accounts/signin.html'
    form_class = SignInForm
    success_url = reverse_lazy('snsapp:home')

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(request=self.request, username=username, password=password)
        if user is not None:
            login(self.request, user)
            return super().form_valid(form)
        else:
            return self.form_invalid(form)

# サインアウト（ログアウト）
def signout(request):
    if request.method == 'POST':
        logout(request)
        return redirect('accounts:index')
    return render(request, 'accounts/signout.html')

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}タイトル{% endblock %}</title>
    <!-- 各種サイトの引用 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
</head>
<body>
    <header>
        {% block header %}
            <nav class="navbar navbar-expand-lg navbar-light bg-light" style="box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
                <div class="container">
                    <div class="col-md-6 offset-md-3 text-center"  style="font-family: 'Shadows Into Light', cursive;">
                        <a class="navbar-brand" href="{% url 'accounts:index' %}">
                            <span class="material-icons" style="font-size: 20px; vertical-align: middle; color: #4D4D4D;">pets</span>
                            <span style="vertical-align: middle; color: #4D4D4D;">Hamtter</span>
                        </a>
                    </div>
                </div>
            </nav>
        {% endblock %}
    </header>

    <main class="mt-4 mb-4">
        {% block content %}
        {% endblock %}
    </main>
    
    <footer style="box-shadow: 0 -2px 4px rgba(0,0,0,0.1);">
        {% block footer %}
        <div class="text-center bg-light py-3"  style="font-family: 'Shadows Into Light', cursive;">
            <p>&copy;2024 Hamtter.com</p>
        </div>
        {% endblock %}
        <hr class="mt-0 mb-2" style="border-top: 1px solid #4D4D4D;">
    </footer>
</body>
</html>

accounts/templates/accounts/index.html
{% extends 'accounts/base.html' %}

{% block title %}Ham -index-{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3" style="font-family: 'Shadows Into Light', cursive;">
                <!-- 説明文・紹介文をいれようかな・・・？ -->
                <div class="text-center mt-2">
                    <h4>Welcome to Hamtter</h4>
                    <br>
                    <div style="font-size: small;">
                        <p>
                            <span>ここではみんなと投稿をシェアできます</span>
                            <br>
                            <span>じぶんの気持ちや思い出をつぶやきましょう！</span>
                            <br>
                            <span>Hamtterのなかまになりましょう！</span>
                            <br>
                            <br>
                        </p>
                    </div>
                </div>

                <div class="text-center mt-4">
                    <!-- サインアップページへの移動 -->
                    <a href="{% url 'accounts:signup' %}" class="btn btn-secondary rounded-pill px-4 py-2 me-2">
                        <i class="fas fa-user-plus fa-lg me-2"></i> signup
                    </a>
                </div>
                <div class="text-center mt-4">
                    <!-- ログインページへの移動 -->
                    <a href="{% url 'accounts:signin' %}" class="btn btn-outline-secondary rounded-pill px-4 py-2 me-2">
                        <i class="fas fa-sign-in-alt fa-lg me-2"></i> login
                    </a>
                </div>
                <br>
                <br>
                <br>
                <br>
                <br>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/signin.html
{% extends 'accounts/base.html' %}

{% block title %}Ham -LOGIN-{% endblock %}

{% block content %}
<div class="container" style="font-family: 'Shadows Into Light', cursive;">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h2 class="card-title text-center mb-4">Login</h2>
                    <!-- エラーメッセージ（機能しているかわからない） -->
                    {% if error_message %}
                    <div class="alert alert-danger" role="alert">{{ error_message }}</div>
                    {% endif %}
                    <!-- ログインのフォーム -->
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_username" class="form-label"><i class="fas fa-user" style="font-size: small;"></i> username</label>
                            <input type="text" name="username" class="form-control rounded-pill" id="id_username" placeholder="ユーザー名を入力してください" style="font-size: small;">
                        </div>
                        <div class="mb-3">
                            <label for="id_password" class="form-label"><i class="fas fa-key" style="font-size: small;"></i> password</label>
                            <input type="password" name="password" class="form-control rounded-pill" id="id_password" placeholder="パスワードを入力してください" style="font-size: small;">
                        </div>
                        <br>
                        <div class="mb-3 text-center">
                            <button type="submit" class="btn btn-outline-primary btn btn-block rounded-pill">Login</button>
                        </div>
                    </form>
                    <!-- サインアップページへの移動 -->
                    <div class="text-center mt-3">
                        <p class="mb-0">アカウントをお持ちでない方は</p>
                        <a href="{% url 'accounts:signup' %}" class="btn btn-link">
                            <i class="fas fa-sign-in-alt me-1"></i> 新規登録
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/signout.html
{% extends 'base.html' %}

{% block title %}Ham -LOGOUT-{% endblock %}

{% block content %}
<div class="container"  style="font-family: 'Shadows Into Light', cursive;">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h2 class="card-title text-center mb-4">ログアウト</h2>
                    <p class="text-center">本当にログアウトしますか？</p>
                    <div class="text-center mt-3">
                        <!-- ログアウトのフォーム -->
                        <form method="post" action="{% url 'accounts:signout' %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-primary rounded-pill me-3">はい</button>
                            <a href="{% url 'snsapp:profile' %}" class="btn btn-outline-secondary rounded-pill">いいえ</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'accounts/base.html' %}

{% block title %}Ham -SIGNUP-{% endblock %}

{% block content %}
<div class="container"  style="font-family: 'Shadows Into Light', cursive;">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h2 class="card-title text-center mb-4">Sign Up</h2>
                    <!-- サインアップのフォーム -->
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_username" class="form-label"><i class="fas fa-user" style="font-size: small;"></i> username</label>
                            <input type="text" name="username" class="form-control rounded-pill" id="id_username" placeholder="ユーザー名を入力してください" style="font-size: small;">
                        </div>
                        <div class="mb-3">
                            <label for="id_email" class="form-label"><i class="fas fa-envelope" style="font-size: small;"></i> email</label>
                            <input type="email" name="email" class="form-control rounded-pill" id="id_email" placeholder="メールアドレスを入力してください" style="font-size: small;">
                        </div>
                        <div class="mb-3">
                            <label for="id_password" class="form-label"><i class="fas fa-key" style="font-size: small;"></i> password</label>
                            <input type="password" name="password" class="form-control rounded-pill" id="id_password" placeholder="パスワードを入力してください" style="font-size: small;">
                        </div>
                        <br>
                        <div class="mb-3 text-center">
                            <button type="submit" class="btn btn-outline-primary btn btn-block rounded-pill mx-auto">Sign Up</button>
                        </div>
                    </form>


                    <!-- <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <p>
                                {{ field.label_tag }}<br>
                                {{ field }}
                            </p>
                        {% endfor %}
                        <input type="submit" value="Sign Up">
                    </form> -->
                    
                    <!-- ログインページへの移動 -->
                    <div class="text-center mt-3">
                        <p class="mb-0">アカウントをお持ちの方は</p>
                        <a href="{% url 'accounts:signin' %}" class="btn btn-link">
                            <i class="fas fa-sign-in-alt me-1"></i> ログイン
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}