accounts/urls.py
from django.urls import path
from . import views
from .views import SignUpView, SignInView
from django.contrib.auth.decorators import login_required


app_name = 'accounts'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signin/', SignInView.as_view(), name='signin'),

    # ログアウトは認証後に使うものなので login_required
    path('signout/', login_required(views.signout), name='signout'),
]

snsapp/urls.py
from django.urls import path
from .views import HomeView,MyHomeView,PostCreateView,PostDeleteView,PostDetailView,PostEditView,ProfileView,ProfileCreateView,ProfileEditView
from django.contrib.auth.decorators import login_required


app_name = 'snsapp'

urlpatterns = [
    path('', login_required(HomeView.as_view()), name='home'),
    path('my_home/', login_required(MyHomeView.as_view()), name='my_home'),
    path('create/', login_required(PostCreateView.as_view()), name='post_create'),
    path('post/<int:pk>/delete/', login_required(PostDeleteView.as_view()), name='post_delete'),
    path('post/<int:pk>/', login_required(PostDetailView.as_view()), name='post_detail'),
    path('post/<int:pk>/edit/', login_required(PostEditView.as_view()), name='post_edit'),
    path('profile/', login_required(ProfileView.as_view()), name='profile'),

    # 機能していないプロフィール関連のurl
    path('profile/create/', login_required(ProfileCreateView.as_view()), name='profile_create'),
    path('profile/edit/', login_required(ProfileEditView.as_view()), name='profile_edit'),
]

snsproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # 追加
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('snsapp.urls')),
]

# メディアファイルの設定
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 追加

snsapp/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='ログインユーザー名',on_delete=models.CASCADE, null=True)
    title = models.CharField("タイトル", max_length=200)
    image = models.ImageField(upload_to='images', verbose_name='画像', null=True, blank=True)
    content = models.TextField("本文")
    updated_at = models.DateTimeField("更新日", auto_now=True)
    created_at = models.DateTimeField("作成日", auto_now_add=True)

    def __str__(self):
        return self.title




# 機能していません
class Profile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='ログインユーザー名', on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100, verbose_name='名前')
    icon = models.ImageField(upload_to='icons', verbose_name='アイコン', null=True, blank=True)
    text = models.TextField("自己紹介文")
    updated_at = models.DateTimeField("更新日", auto_now=True)
    created_at = models.DateTimeField("作成日", auto_now_add=True)

    def __str__(self):
        return self.name

snsapp/forms.py
# snsapp/forms.py
from django import forms
from .models import Post,Profile

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'image', 'content']

class PostEditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'image','content']




# 使うかわからないプロフィール
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'icon', 'text']

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'icon', 'text']

snsapp/views.py
from django.shortcuts import redirect
from django.views.generic.edit import UpdateView
from .models import Post, Profile
from .forms import PostEditForm,PostForm,ProfileEditForm,ProfileForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView,CreateView,DeleteView,DetailView,UpdateView,ListView


class HomeView(ListView):
    template_name = 'home.html'
    model = Post
    context_object_name = 'posts'
    ordering = ['-created_at']
    
# まだ実装途中
class MyHomeView(ListView):
    template_name = 'my_home.html'
    model = Post
    context_object_name = 'user_posts'
    ordering = ['-created_at']

    def get_queryset(self):
        return Post.objects.filter(user=self.request.user)

# 作成時のログインユーザーのユーザー名を投稿者としたい
class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'post_create.html'
    success_url = reverse_lazy('snsapp:home')

    def form_valid(self, form):
        form.instance.user = None
        return super().form_valid(form)
    
    # これはプロフィールの名前やアイコン、自己紹介文を実装した場合のもの
    #def form_valid(self, form):
    #    profile = Profile.objects.get(user=self.request.user)
    #    form.instance.user = profile.name
    #    return super().form_valid(form)
    

# 投稿削除
class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('snsapp:home')
    template_name = 'post_delete.html'

# 投稿詳細
class PostDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'
    context_object_name = 'post'

# 投稿編集
class PostEditView(UpdateView):
    model = Post
    form_class = PostEditForm
    template_name = 'post_edit.html'

    def form_valid(self, form):
        form.save()
        return redirect('snsapp:home')

# プロフィール
class ProfileView(TemplateView):
    template_name = 'profile.html'



# 使うかわからないプロフィール
class ProfileCreateView(CreateView):
    model = Profile
    form_class = ProfileForm
    template_name = 'profile_create.html'
    success_url = reverse_lazy('snsapp:profile')

    def form_valid(self, form):
        form.instance.user = None
        return super().form_valid(form)
    
class ProfileEditView(UpdateView):
    model = Profile
    form_class = ProfileEditForm
    template_name = 'profile_edit.html'

    def form_valid(self, form):
        form.save()
        return redirect('snsapp:profile')

snsapp/templates/base.html
<!-- {% load static %} -->
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Hamtter{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"> -->
</head>
<body>
    <header>
        {% block header %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light" style="box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
            <div class="container">
                <!-- 1列目　タイトル -->
                <div class="col-md-6 text-center" style="font-family: 'Shadows Into Light', cursive;">
                    <a class="navbar-brand" href="#">
                        <span class="material-icons" style="font-size: 20px; vertical-align: middle; color: #4D4D4D;">pets</span>
                        <span style="vertical-align: middle; color: #4D4D4D;">Hamtter</span>
                    </a>
                </div>                
                
                <!-- ナビゲーションリンク -->
                <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item"><a class="nav-link" href="#"><span class="material-icons"  style="font-size: 24px; vertical-align: middle;">help_outline</span></a></li>
                        <li class="nav-item"><a class="nav-link" href="#">LI2</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'snsapp:home' %}"><span class="material-symbols-outlined" style="font-size: 24px; vertical-align: middle;">home</span></a></li>
                        <li class="nav-item"><a class="nav-link" href="#">LI3</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'snsapp:profile' %}"><span class="material-symbols-outlined" style="font-size: 24px; vertical-align: middle;">person</span></a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <hr class="mt-0 mb-2" style="border-top: 1px solid #4D4D4D;">
        {% endblock %}
    </header>

    <main class="mt-4 mb-4">
        {% block content %}
        {% endblock %}
    </main>
    
    <footer style="box-shadow: 0 -2px 4px rgba(0,0,0,0.1);">
        {% block footer %}
        <div class="text-center bg-light py-3"  style="font-family: 'Shadows Into Light', cursive;">
            <p>&copy;2024 Hamtter.com</p>
        </div>
        {% endblock %}
        <hr class="mt-0 mb-2" style="border-top: 1px solid #4D4D4D;">
    </footer>
    
</body>
</html>

snsapp/templates/home.html
{% extends 'base.html' %}

{% block title %}Ham -HOME-{% endblock %}

{% block content %}
<div class="container">
    <div class="text-center" style="font-family: 'Shadows Into Light', cursive;">
        <div style="font-size: smaller;">
        Home-Resident User
        </div>
        <p>
            <span style="width: 7px; height: 7px; border-radius: 50%; display: inline-block; background-color: rgb(0, 190, 0); margin-right: 2px; box-shadow: 0 0 10px green;"></span>
            <span>{{ user.username }}</span>
        </p>
    </div>
    <div class="text-center">
        <a href="{% url 'snsapp:post_create' %}" class="btn btn-outline-dark btn-sm mb-4"  style="box-shadow: 0 4px 8px rgba(0,0,0,0.1); font-family: 'Shadows Into Light', cursive;">
            <i class="fas fa-plus"></i> 投稿
        </a>
    </div>

    <div class="row justify-content-center mt-3">
        <div class="col-md-8">
            <!-- 投稿一覧をまとめたカード -->
            <div class="card" style="box-shadow: 0 4px 8px rgba(0,0,0,0.1);">
                <!-- カードのヘッダー -->
                <div class="card-header bg-white" style="font-family: 'Shadows Into Light', cursive;">
                    <div class="d-flex justify-content-between align-items-center">
                        <h3 class="m-0" style="color: #595959;">
                            <span style="margin-left: 10px; color: #595959;"><i class="fas fa-seedling"></i></span>
                            Post
                        </h3>
                    </div>
                </div>
                <!-- カードの本体（投稿の表示） -->
                <div class="card-body" style="font-family: 'Shadows Into Light', cursive;">
                    {% for post in posts %}
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="d-flex justify-content-between align-items-center">
                                <!-- 投稿のタイトル -->
                                <h5 class="card-title font-weight-bold mb-0" style="margin-left: 5px;">
                                    <a href="{% url 'snsapp:post_detail' post.pk %}" class="text-decoration-none" style="color: #595959;">{{ post.title }}</a>
                                </h5>
                                <!-- 投稿者 -->
                                <small class="text-muted d-flex align-items-center" style="margin-right: 5px;">
                                    <i class="fas fa-user-circle me-2" style="font-size: 1.5rem;"></i><span>{{ post.user }}</span>
                                </small>                               
                            </div>
                            <hr class="my-2">
                            <!-- 投稿の本文 -->
                            <p class="card-text mb-1" style="color: #4D4D4D; margin-left: 5px;">{{ post.content }}</p>
                            <!-- 投稿の画像（投稿時に画像があれば・・・） -->
                            {% if post.image %}
                            <img src="{{ post.image.url }}" class="card-img-top mt-2" alt="{{ post.title }}">
                            {% endif %}
                        </div>
                        <!-- 投稿ごとの各機能（詳細・編集・削除）本来はMyHomeページのみで使うもの -->
                        <div class="card-footer bg-white">
                            <div class="d-flex justify-content-between align-items-center">
                                <div>
                                    <a href="{% url 'snsapp:post_detail' post.pk %}" class="btn btn-link" title="詳細ページに移動します"><i class="fas fa-file" style="color: #C0C0C0;"></i></a><!--詳細-->
                                    <a href="{% url 'snsapp:post_edit' post.pk %}" class="btn btn-link" title="編集ページに移動します"><i class="fas fa-edit" style="color: #C0C0C0;"></i></a><!--編集-->
                                    <a href="{% url 'snsapp:post_delete' post.pk %}" class="btn btn-link" title="削除ページに移動します"><i class="fas fa-trash-alt" style="color: #C0C0C0;"></i></a><!--削除-->
                                </div>
                                <!-- 投稿時の時間の表示 -->
                                <small class="text-muted"><i class="far fa-clock"></i> {{ post.created_at|date:"Y/m/d H:i" }}</small>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            
        </div>
    </div>
</div>

{% endblock %}

snsapp/templates/my_home.html
{% extends 'base.html' %}

{% block title %}My Home{% endblock %}

{% block content %}
<div class="container">
    <div class="text-center">
        <a href="{% url 'snsapp:post_create' %}" class="btn btn-outline-dark btn-sm mb-4" style="box-shadow: 0 4px 8px rgba(0,0,0,0.1);">
            <i class="fas fa-plus"></i> 投稿
        </a>
    </div>


    <!-- ユーザー認証ができ次第、HomeとMyHomeの分割を実装 -->
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card" style="box-shadow: 0 4px 8px rgba(0,0,0,0.1);">
                <div class="card-header bg-white">
                    <div class="d-flex justify-content-between align-items-center">
                        <h3 class="m-0" style="color: #595959;">
                            <span style="margin-left: 10px; color: #595959;"><i class="fas fa-clipboard"></i></span>
                            My Posts
                        </h3>
                    </div>
                </div>
                <div class="card-body" style="font-family: 'Shadows Into Light', cursive;">
                    {% if user_posts %}
                        {% for post in user_posts %}
                            <div class="card mb-3">
                                <div class="card-body">
                                    <div class="d-flex justify-content-between align-items-center">
                                        <h5 class="card-title font-weight-bold mb-0" style="margin-left: 5px;">
                                            <a href="{% url 'snsapp:post_detail' post.pk %}" class="text-decoration-none" style="color: #595959;">{{ post.title }}</a>
                                        </h5>
                                        <small class="text-muted d-flex align-items-center" style="margin-right: 5px;">
                                            <i class="fas fa-user-circle me-2" style="font-size: 1.5rem;"></i><span>{{ post.user }}</span>
                                        </small>                               
                                    </div>
                                    <hr class="my-2">
                                    <p class="card-text mb-1" style="color: #4D4D4D; margin-left: 5px;">{{ post.content }}</p>
                                    {% if post.image %}
                                        <img src="{{ post.image.url }}" class="card-img-top mt-2" alt="{{ post.title }}">
                                    {% endif %}
                                </div>
                                <div class="card-footer bg-white">
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div>
                                            <a href="{% url 'snsapp:post_detail' post.pk %}" class="btn btn-link" title="詳細ページに移動します"><i class="fas fa-file" style="color: #C0C0C0;"></i></a><!--詳細-->
                                            <a href="{% url 'snsapp:post_edit' post.pk %}" class="btn btn-link" title="編集ページに移動します"><i class="fas fa-edit" style="color: #C0C0C0;"></i></a><!--編集-->
                                            <a href="{% url 'snsapp:post_delete' post.pk %}" class="btn btn-link" title="削除ページに移動します"><i class="fas fa-trash-alt" style="color: #C0C0C0;"></i></a><!--削除-->
                                        </div>
                                        <small class="text-muted"><i class="far fa-clock"></i> {{ post.created_at|date:"Y/m/d H:i" }}</small>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <p>No posts yet.</p>
                        <p>ログイン中ユーザーの投稿がありません</p>
                    {% endif %}
                </div>
            </div>  
        </div>
    </div>
</div>

{% endblock %}

snsapp/templates/post_create.html
{% extends 'base.html' %}

{% block title %}Ham -POST-{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3" style="font-family: 'Shadows Into Light', cursive;">
            <h2 class="text-center mb-4">new post</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <!-- タイトル入力フォーム -->
                <div class="mb-3">
                    <label for="id_title" class="form-label"><i class="fas fa-leaf"></i> title</label>
                    <input type="text" class="form-control" id="id_title" name="title" placeholder="タイトルを入力してください">
                </div>
                <!-- 画像選択フォーム -->
                <div class="mb-3">
                    <label for="id_image" class="form-label"><i class="fas fa-image"></i> picture</label>
                    <input type="file" class="form-control" id="id_image" name="image" onchange="previewImage(this)">
                    <img id="imagePreview" class="mt-2 img-thumbnail mx-auto d-block" style="display: none; max-width: 200px;">
                </div>
                
                <!-- 本文入力フォーム -->
                <div class="mb-3">
                    <label for="id_content" class="form-label"><i class="fas fa-pencil-alt"></i> content</label>
                    <textarea class="form-control" id="id_content" name="content" rows="5" placeholder="内容を入力してください"></textarea>
                </div>
                <!-- 投稿ボタン -->
                <div class="text-center">
                    <button type="submit" class="btn btn-outline-primary"><i class="fas fa-paper-plane"></i> 投稿する</button>
                    <a href="javascript:history.back()" class="btn btn-outline-secondary">
                        <i class="fas fa-arrow-left"></i> 戻る
                    </a>
                    
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

snsapp/templates/post_delete.html
{% extends 'base.html' %}

{% block title %}Ham -DELETE-{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center"  style="font-family: 'Shadows Into Light', cursive;">
        <div class="col-md-6">
            <h2 class="text-center mb-4">delete post</h2>
            <p class="text-center">以下の投稿を削除します。よろしいですか？</p>
            <!-- 削除予定の投稿を再表示 -->
            <div class="card">
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><strong>title:</strong> {{ object.title }}</li>
                        <li class="list-group-item"><strong>content:</strong> {{ object.content }}</li>
                        {% if post.image %}
                        <img src="{{ post.image.url }}" class="img-fluid" alt="{{ post.title }}">
                        {% endif %}
                    </ul>
                </div>
                <div class="card-footer text-center">
                    <!-- 削除の確定 -->
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-danger mx-2">削除</button>
                        <a href="{% url 'snsapp:home' %}" class="btn btn-outline-secondary mx-2">キャンセル</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

snsapp/templates/post_detail.html
{% extends 'base.html' %}

{% block title %}Ham -DETAIL-{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8" style="font-family: 'Shadows Into Light', cursive;">
            <h2 class="text-center mb-4">details</h1>
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">{{ post.title }}</h3>
                    <p class="card-text">{{ post.content }}</p>
                    {% if post.image %}
                        <img src="{{ post.image.url }}" class="img-fluid" alt="{{ post.title }}">
                    {% endif %}
                </div>
                <div class="card-footer text-center">
                    <a href="javascript:history.back()" class="btn btn-outline-secondary">
                        <i class="fas fa-arrow-left"></i> 戻る
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

snsapp/templates/post_edit.html
{% extends 'base.html' %}

{% block title %}Ham -EDIT-{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3"  style="font-family: 'Shadows Into Light', cursive;">
            <h1 class="text-center mb-4">edit post</h1>
            <form method="post">
                {% csrf_token %}
                <!-- タイトル入力フォーム -->
                <div class="mb-3">
                    <label for="id_title" class="form-label"><i class="fas fa-leaf"></i> title</label>
                    <input type="text" class="form-control" id="id_title" name="title" value="{{ post.title }}">
                </div>
                <!-- 画像選択フォーム -->
                <div class="mb-3">
                    <label for="id_image" class="form-label"><i class="fas fa-image"></i> picture</label>
                    <input type="file" class="form-control" id="id_image" name="image">
                </div>
                
                <!-- 本文入力フォーム -->
                <div class="mb-3">
                    <label for="id_content" class="form-label"><i class="fas fa-pencil-alt"></i> content</label>
                    <textarea class="form-control" id="id_content" name="content" rows="5">{{ post.content }}</textarea>
                </div>
                <!-- 更新ボタン -->
                <div class="text-center">
                    <button type="submit" class="btn btn-outline-primary"><i class="fas fa-sync"></i> 更新</button>
                    <a href="javascript:history.back()" class="btn btn-outline-secondary">
                        <i class="fas fa-arrow-left"></i> 戻る
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

snsapp/templates/profile.html
{% extends 'base.html' %}

{% block title %}プロフィール{% endblock %}

{% block content %}
<div class="container" style="font-family: 'Shadows Into Light', cursive;">
    <h1 class="text-center mb-4">profile</h1>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"><i class="fas fa-user-circle me-2" style="font-size: 1.5rem;"></i> {{ user.username }}</h5>
                    <p class="card-text">ここにユーザーのプロフィール情報を表示します。まだ実装できていないため、仮の文章を書いておきます</p>
                </div>
            </div>
            <!-- 機能なし -->
            <div style="text-align: center;" class="mt-4">
                <a href="{% url 'snsapp:my_home' %}" class="btn btn-outline-dark mt-3">
                    <i class="fas fa-home"></i> My Home
                </a>
            </div>
            <!-- ログアウトページへ移動 -->
            <div style="text-align: center;" class="mb-4">
                <a href="{% url 'accounts:signout' %}" class="btn btn-outline-danger mt-3">
                    <i class="fas fa-sign-out-alt"></i> ログアウト
                </a>
            </div>
            <div>
                <a href="{% url 'snsapp:home' %}" class="btn btn-outline-secondary mt-3">
                    <i class="fas fa-arrow-left"></i> 戻る
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

snsapp/templates/profile_create.html
{% extends 'base.html' %}

{% block title %}プロフィール作成{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center mb-4">プロフィール作成</h1>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary mt-3">作成する</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

snsapp/templates/profile_edit.html
{% extends 'base.html' %}

{% block title %}プロフィール編集{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-center mb-4">プロフィール編集</h1>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary mt-3">保存する</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}